### ISSUE TITLE
Matlab data

### ISSUE THREAD

**Issue by Zgb5566113** [Gabalo/RO_PUF#2]
Hello, thanks for your previous reply. According to your instructions, I adopted Xilinx Nexys 4-100T Aritil-7 CSG324 FPGA for comprehensive implementation in Vivado, but the number of IO ports would exceed the resources of development office. Therefore, I used Xilinx Nexys 4-200T Aritil-7 development board to successfully burn ro-PUF, and received data from FPGA through Matlab. What I am confused about is the intense input
![Matlab data](https://user-images.githubusercontent.com/82522184/131611659-40a61f7a-4188-41ab-91cc-f8f6f4565a1a.PNG)
![over IO sourse](https://user-images.githubusercontent.com/82522184/131611661-747d13dd-5911-47c6-b784-be51b1dcb40e.PNG)

**Comment by Gabalo** [comment]
I didn't have any utilization issue on my board. What the Matlab script is doing is simply writing byte by byte, from 0x00 to 0xFF, through the UART. The UART controller on the FPGA receives each byte, the PUF generates the response and the UART controller writes it back (33 bytes) byte by byte.

**Comment by Zgb5566113** [comment]
Thank you for your answer. Is there any error in the running result of my matlab program? In addition, which file did you store the response generated by PUF?
![Matlab data](https://user-images.githubusercontent.com/82522184/131668199-bc55cd84-8661-4e4a-b5a3-aa06872d845f.PNG)
