### ISSUE TITLE
Import Design Sources for built Project

### ISSUE THREAD

**Issue by wzu0** [Gabalo/RO_PUF#4]
Hello, thank you for sharing. I'm a graduate student from Wenzhou University. In order to create a project, I encountered some problems when importing the design resources you shared.  The problem is as follows: when importing xilinx_ decoder(one file from your shared files), you will be asked to add "u_ pipeline:xil_ defaultlib.pipeline"  this  file,but I did not find this file in the folder you shared.Besides，when you add the file"bch_syndrome(one file in you BCH files)", you will be asked to add other files that do not exist in your file in the sub file folder. The development platform I use is vivado 2019.3 .
![11](https://user-images.githubusercontent.com/90365638/132613288-baf5e216-9654-439e-a325-4ae18aa461e0.PNG)
![22](https://user-images.githubusercontent.com/90365638/132613295-7c78162d-2b1f-4b25-9c19-c50838131aa1.PNG)
I don't know how to solve this problem. Can you help me see the problem?

**Comment by Gabalo** [comment]
Hi wzu0, the BCH module is from Russ Dill's project [https://github.com/russdill/bch_verilog], please refer to it if you have specific questions regarding the files. My project uses the basic BCH encoding functionality from it, so not all files/modules are needed. 

I should credit his work on my repo, thanks for noticing.
