### ISSUE TITLE
About BCH error

### ISSUE THREAD

**Issue by wzu0** [Gabalo/RO_PUF#5]
Hello, according to your prompt, I interviewed the author of BCH, He told me the reason for the error was using a fake (and thus missing) symbolname to indicate a configuration error. I've set the "pipeline_stages"parameter to a value greater than 2, which isn't supported by that module（bch_syndrome_method2).  I looked at the corresponding BCH code but don't know how to modify it or if you have more than 2 "pipeline_stages" in your design. In addition,by ignoring these errors, I can generate bitstream files, however, randomness of response is not well compared to the bitstream file you shared. What should I do to solve these problems?
![11](https://user-images.githubusercontent.com/90365638/133022429-4078f1e7-2eba-4d8c-8cfe-2a08ba56d3e6.PNG)
![22](https://user-images.githubusercontent.com/90365638/133022436-71b7651b-031e-439e-9930-81ece120f8a4.PNG)

**Comment by Gabalo** [comment]
As the author of the BCH encoder mentioned in his project, the number of pipeline stages is one of the parameters in the modules. I think it is pretty clear to see (and modify) if you read the code. As for the response of the PUF, if you don't see any indication of an error in any of the internal modules, I recommend you play around with the placement of the ring oscillators. This can be done modifying the Pblocks in the constrains file or directly in the Vivado GUI.
